### ISSUE TITLE
provision a Kubernetes cluster to deploy into

### ISSUE THREAD

**Issue by yuluqinn** [Products-Development-Team/products#10]
**As a** User
**I need** the service to be publicly available on Kubernetes
**So that** I can use it from the Internet 

### Acceptance Criteria

 ```gherkin
Given I have created the required files to deploy service on Kubernetes
When I issue a `kubectl apply -f deploy`
Then the service successfully deploys to Kubernetes
 ```

**Comment by dd3053** [comment]
I think we can write something like : 

As a User
I need the service to be publicly available on Kubernetes
So that I can use it from the Internet

Additionally, can we consider it as user enhancement ?

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/10?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
