### ISSUE TITLE
Need the ability to list products by price

### ISSUE THREAD

**Issue by yuluqinn** [Products-Development-Team/products#12]
**As a** Shopper  
 **I need** to see all products within a price range
 **So that** I can filter out the items that are not in my budget

 ### Details and Assumptions
 * Must be RESTful
 * The endpoint must be /products
 * Use GET
 * Add query capability to the model
 * Add query string support to the List function
 
 ### Acceptance Criteria  
 ```gherkin

Given I have set the price maximum to be 200
When we call GET /products?price=200
Then return a collection of products with price lower or equal to 200

 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/12?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
