### ISSUE TITLE
Need the ability to list by rating

### ISSUE THREAD

**Issue by yuluqinn** [Products-Development-Team/products#13]
**As a** Shopper  
 **I need** to refer to the rating of products
 **So that** I can reduce my risk of purchasing unwanted items

 ### Details and Assumptions
 * Must be RESTful
 * The endpoint must be /products
 * Use GET
 * Rating ranges from 1-5, 1 stands for the lowest and 5 is the highest. 
 * Add query capability to the model
 * Add query string support to the List function
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the need of knowing the rating of products
 When I call GET /products?rating=3
 Then GET should return a collection of products with rating higher or equal to 3. 
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/13?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn

**Comment by dd3053** [comment]
I have suggestion for you :
Be more specific for the user

**Comment by hxwang-463** [comment]
It says in homework that "What I am look for is that your existing List endpoint can accept a query string to filter the results returned, and...", therefore I am not going to create a new endpoint here. I will update the # LIST ALL PRODUCTS function and add test cases.
