### ISSUE TITLE
Ability to List all the Products

### ISSUE THREAD

**Issue by dd3053** [Products-Development-Team/products#14]
**As a** User
 **I need** to list all the products  
 **So that** I can verify whether all the product entries are correctly made.
   
 ### Details and Assumptions
 * Use `GET /products` to fetch the list of all products. 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given The Server is running 
 When the GET /products request is made
 Then a JSON file is returned which contains the details of all the products.
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/14?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn

**Comment by yuluqinn** [comment]
I think this is enhancement

**Comment by xiaokailll** [comment]
Also I think this is not only for Application Developer, but for User as well.

**Comment by yuluqinn** [comment]
I agree.

**Comment by yuluqinn** [comment]
Suggestion: change technical debt to enhancement, and change developer to User
