### ISSUE TITLE
Need the ability to create a new product

### ISSUE THREAD

**Issue by xiaokailll** [Products-Development-Team/products#2]
**As a** product manager
 **I need** to be able to create a new product
 **So that** I can create a new product with its ID, name, description, price, etc
   
 ### Details and Assumptions
 * Use POST function
 * Each product will be assign a unique ID
 * The endpoint must be called /products
 * When creating a new product, you must specify the ID in path like '/products/12345'
 * Other information like name, description, price, etc, will be in the body of POST call.
 * return code:  
201_CREATED
409_CONFLICT
   
 ### Acceptance Criteria  

 ```gherkin  
 Given I have a Product Service
 When I call POST products/[new_product_ID], with the body of name, description, price, etc
 Then I created a product with ID [new_product_ID]
 ```

**Comment by yuluqinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/2?planning-poker) with ZenHub @dggjsc @dd3053 @mpourostad @xiaokailll

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/2?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
