### ISSUE TITLE
Need the ability to update a product

### ISSUE THREAD

**Issue by mpourostad** [Products-Development-Team/products#3]
**As a** Manager
 **I need** to be able to update the information on the existing products,
 **So that** the customers can view the updated details of a product
   
 ### Details and Assumptions
* Use the HTTP PUT verb to update a resource
* Assuming the product that needs to be updated already exists in the system.
* The product unique id cannot be updated. 
* Successful return codes:
      - 200_OK: If a resource exists and can be updated by the server and returned.
      - 404_NOT_FOUND: If the resource doesn't exist
 ### Acceptance Criteria
   
 ```gherkin
 Given  I have a product service
 When I call PUT /products/123
 Then the product with an id of 123 should be updated with the new data
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/3?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
