### ISSUE TITLE
Set up environment to  deploy application on IBM cloud

### ISSUE THREAD

**Issue by dggjsc** [Products-Development-Team/products#44]
**As a** developer
 **I need** the ability to deploy the app to the cloud
 **So that**  I can deploy the microservice on IBM Cloud
   
 ### Details and Assumptions
 * Create a Kubernetes cluster on IBM Cloud.
 * Update the devcontainer environment to download and install the IBM Cloud CLI
 * Create the necessary Kubernetes metadata files for deployment
 * Use the Kubernetes CLI  to deploy our service to Kubernetes cluster.
 
  
 ### Acceptance Criteria  
   
 ```gherkin
 When  I access the URL of my service
 Then   I can access my service and use its functions
 ```

**Comment by yuluqinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/44?planning-poker) with ZenHub @dd3053 @dggjsc @hxwang-463 @mpourostad
