### ISSUE TITLE
Need the ability to query a product

### ISSUE THREAD

**Issue by dggjsc** [Products-Development-Team/products#45]
**As a** user
 **I need** the ability to query the product information based on personalized filters I set up
 **So that** I can get the detail information of a product I'm looking for.
   
 ### Details and Assumptions
 * Create RESTful API that has query function
 * Add query string support to List function
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have a product service
 When the GET /products request is made
 Then a JSON file is returned which contains the details of a product I query
 ```

**Comment by yuluqinn** [comment]
We currently have list by rating and list by price, perhaps we can add a bit more

**Comment by yuluqinn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/45?planning-poker) with ZenHub @dd3053 @dggjsc @hxwang-463 @mpourostad
