### ISSUE TITLE
Need an action to update the price attribute

### ISSUE THREAD

**Issue by yuluqinn** [Products-Development-Team/products#46]
**As a** shop manager
 **I need** to update the price of a product 
 **So that** I can easily adjust the price according to market change

 ### Details and Assumptions
 * Through a request, a shop manager can update the price attribute of a product without editing all attributes about a product
 * Need to create a new endpoint that ends with /reset-price
 *  Need to follow the REST API guidelines learned in class for
actions.

 ### Acceptance Criteria  
   
 ```gherkin
 Given the need to update the price of a product 
 When PUT /products/{id}/price with the the new price
 Then the price state of the product with {id} will be changed to the new price. 
 ```

**Comment by dd3053** [comment]
Do we need to modify this user story to include something like `customer_id` as well ?
