### ISSUE TITLE
Need the ability to delete a product 

### ISSUE THREAD

**Issue by yuluqinn** [Products-Development-Team/products#5]
**As a** Marketing manager
 **I need** the ability to delete a product
 **So that** I can remove products that are no longer for sale
   
 ### Details and Assumptions
 * The API must be RESTful.
 * The endpoint must be called /products.
 * Delete the product based on product Id
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have a product with product Id '12345'
 When I call DELETE /products/12345
 Then I get back 204 No Content
 ```

**Comment by xiaokailll** [comment]
I think we can use the ID to delete the product, in order to be consistent with the Create and Update.
Like DELETE /products/12345

**Comment by yuluqinn** [comment]
> I think we can use the ID to delete the product, in order to be consistent with the Create and Update. Like DELETE /products/12345

sounds good. Thanks

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/5?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
