### ISSUE TITLE
Add Information about the Products Service (Root URL)

### ISSUE THREAD

**Issue by dd3053** [Products-Development-Team/products#7]
**As a** User 
 **I need** to know the details about the Service 
 **So that** I can know about the resource and its usage.
   
 ### Details and Assumptions
 * GET Request to `/` (Root URL) should return the name, version  resource URL's and the usage information.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given The Server is available 
 When I send a GET Request to / (Root URL)
 Then I will get the name, version , resource URL's and the usage information.
 ```

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/7?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn

**Comment by dd3053** [comment]
- Edit it to '/' (root)

**Comment by yuluqinn** [comment]
Suggestion: GET / or http://localhost:8080/ will return information about the service, while GET /products or http://localhost:8000/products will get a list of products/; Details may include: resources include basic info: name, version, description, and Id
