### ISSUE TITLE
Need the ability to list products by category

### ISSUE THREAD

**Issue by dd3053** [Products-Development-Team/products#8]
**As a** User
 **I need** to get a List of Products of the same category.
 **So that** I can see the products present in a given category.
   
 ### Details and Assumptions
* The base URL is /products
 * URL should return the list of all the products of the particular category.
 * Add query capability to the model
 *  Add query string support to the List function
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given The server is available
 When I send a GET Request to /products?category=shirts
 Then I will get a list of all products having the category as shirts.
 ```

**Comment by yuluqinn** [comment]
List by category/list by name/list by price

**Comment by dd3053** [comment]
> 

Is it. better if we create a Story for each one of them ? I think each one of them will have a different Acceptance Criteria or maybe different use case.

**Comment by yuluqinn** [comment]
> > 
> 
> Is it better if we create a Story for each one of them ? I think each one of them will have a different Acceptance Criteria or maybe different use case.

yes we can try to do that, name/category maybe similar(get /<name>, get /<category>, price would definitely be different(like list all price > XX or < XX), and if we want we can add more features like rating(similar logic to price I think)

**Comment by dd3053** [comment]
- Edit and make it to list all resources

**Comment by dd3053** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/products-629cdf49faf0b6001abbdd21/issues/Products-Development-Team/products/8?planning-poker) with ZenHub @dggjsc @mpourostad @xiaokailll @yuluqinn
